sudo: required
dist: bionic
language: cpp
matrix:
  include:
  - os: osx
    env: TARGET=darwin MACOSX_DEPLOYMENT_TARGET=10.10
    addons:
      homebrew:
        packages:
        - bison
        - flex
        - gawk
        - git
        - pkg-config
        - gnu-sed
        - wget
        - eigen
  - os: linux
    env: TARGET=linux_x86_64
before_script:
- if [[ ${TARGET:0:7} == "windows" ]]; then sudo dpkg --add-architecture i386; fi
- if [[ "$ARCH" == "linux_i686" ]]; then sudo dpkg --add-architecture i386; fi
- if [[ "$ARCH" == "linux_armv7l" ]]; then sudo dpkg --add-architecture armhf; fi
- if [[ "$ARCH" == "linux_aarch64" ]]; then sudo dpkg --add-architecture arm64; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:tes/ams;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:deadsnakes/ppa;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y -qq; fi
script:
- bash build.sh $TARGET
- openssl sha1 _packages/**/*.tar.gz
deploy:
  provider: releases
  # - Create a `public_repo` GitHub token. Go to: https://github.com/settings/tokens/new
  # - Encrypt it: `travis encrypt 0123456789012345678901234567890123456789
  # - Paste the output down here
  api_key:
    secure: "vbeR2h2fLqBt6uJokd+SQHN7DMMWo0oNViTM0i/pT0aRdCP7GdxjbCtU08y0p9bbdFSiY18JfaKffTEN23quZPt51sexpIQ3Jy3AUTagZguOlp7GdZWZh60chTKsNB0zOj5XAEr5i9ADAi37vR7EOFepxYI4Q9vhE+rCVN+CtLcUORnnR4AXMQY9M3IjzdEjRXa827Bfhe30X884kB3Rq+qCtZttJRCd1f7fm3O7b+gbu5eGS0RQkvV43G4y0VFT1JJ/YMp2KGcZ6wCpkk1+fmgke9AqzyLee+trQGj0D+Qh4ztl0YgUgMJu688/bTbJDskSGgMktNTvkP/ejnbI/ms8OBslYF1Idj+fmUNgJ2nfPxXDCqoWooBp4UMROdU6KwMjkO4nTCFzFcoTHWid+QdGtOI3CmkvmN+xO1/VBUuQKdwnK9VsFWl7Y8wjweSDlvKs97oVXU0nyCmIMoTOUUlrTMuGpQ+FioGYr31/j5ZT9bNiZaXBCusW9ymNvq647JQShd8jVXSqpaiTBE3GRwYnRQvdUUshvFozr+OQFqItgL8KDpC84EjqqhNmhY9ZxwRZ/HV8zTzRS/+olnEf4JKsBNePdfPiC9BFYZTfXugnAkEf7FzD3CzLwz4vEc9KU+QxA4IKZdX9dl+MVF3RIMWJxhyaQTtR0PDblpGPOLA="
  file:
    - _packages/**/*.tar.gz
    - _packages/**/*.zip
  file_glob: true
  skip_cleanup: true
  on:
    repo: xobs/toolchain-nextpnr-ecp5
    all_branches: true
    tags: true
branches:
  only:
    # Release tags
    - /^v\d+\.\d+/
    - master
notifications:
  email:
    on_success: change