sudo: required
dist: trusty
language: cpp
matrix:
  include:
  - os: osx
    env: TARGET=darwin
  - os: linux
    env: TARGET=linux_x86_64
  # - os: linux
  #   env: TARGET=linux_i686
  # - os: linux
  #   env: TARGET=linux_armv7l
  # - os: linux
  #   env: TARGET=linux_aarch64
  # - os: linux
  #   env: TARGET=windows_x86
  # - os: linux
  #   env: TARGET=windows_amd64
before_script:
- if [[ ${TARGET:0:7} == "windows" ]]; then sudo dpkg --add-architecture i386; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
- if [[ ${TARGET:0:7} == "windows" ]]; then sudo add-apt-repository -y ppa:adrozdoff/mingw; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:tes/ams; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:deadsnakes/ppa; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y -qq; fi
script:
- bash build.sh $TARGET
- openssl sha1 _packages/**/*.tar.gz
deploy:
  provider: releases
  api_key:
    secure: x8HOEeoENaA2msv0xmF6hIGsQ5xLxSnRZipxEZGvhc1g9Wd57Jh0Bf3eKwtYbi1m7qc8dTcwrryfD37/SSLs4Cl0xPlQFyBW4Ogcn76HZNSduB5lvf/xRJsAJWIByhhOSbDptgewwpMgorT6M8eQH5vxYrHzgC7qnCKnv5yvE/dJlrsJES27dAHy4DEO653XjdevUBWaJT+8Fi6wkB8D9Xr6ed3p+kEHF2cuM+W9S6sqgvogMGKcfnzk2TSOzOisCWY8AIgkN5yl0GiCCR7dr59X+1t2B/GietBbYuWCTFJqrU0DALTqyg7yBmnl73Jhqs7XeYmoXc6gUTYvvnyRx6oKIoGzJrPe8vJZ0/Ohm/GpQNrkuWD2Smb2dhnF7niLxX0oEz6xXzJ1NZOruPApLdl85oNF0s1sU1FNortOaNsIe4S8CKgGPyOum7V3c1D6JlJIprJ3NSVrbgGMxNTtjeUqgMwfGLItiiwUTyww8woUI6mxLD/ab3NYXXV1WIn80ABacnSDvzsS518czmEpCzz+urFNoOQsFAxUf+DmcDebOhjQ037HjCdKMmZ8ezg0va34nls4g+PBLw8Vt1tX0De1UGwP8obwlrsrtM6KotxCMgFGdlGi5gNXdThR7RNZnOAKx3ml1CcCgtNfsToHbJjFnQM0et7gcx4Am8xqlT0=
  file: _packages/**/*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: xobs/toolchain-icestorm
    all_branches: true
