sudo: required
dist: bionic
language: cpp
matrix:
  include:
  - os: osx
    env: TARGET=darwin MACOSX_DEPLOYMENT_TARGET=10.10
    addons:
      homebrew:
        packages:
        - bison
        - flex
        - gawk
        - cmake
        - git
  - os: linux
    env: TARGET=linux_x86_64
before_script:
- if [[ ${TARGET:0:7} == "windows" ]]; then sudo dpkg --add-architecture i386; fi
- if [[ "$ARCH" == "linux_i686" ]]; then sudo dpkg --add-architecture i386; fi
- if [[ "$ARCH" == "linux_armv7l" ]]; then sudo dpkg --add-architecture armhf; fi
- if [[ "$ARCH" == "linux_aarch64" ]]; then sudo dpkg --add-architecture arm64; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y -qq; fi
script:
- bash build.sh $TARGET
- openssl sha1 _packages/**/*.tar.gz
deploy:
  provider: releases
  api_key:
    secure: "u73N97mN+GM66t/DwLkccz8PupxAuIvs0ZlVS4rN+y85B9YzL7lR5b2cK79fCNEfhgJDl+l5AobbBA9+4pj+C6kY9EAeJD4grMAjTVJ3JEolgrfZyRt1Rw4kqQLxhF1kIpn/y6S5H0CzvzIQ8eLfD69DjIuobTVJKRrQrZuK+jgTOF2WGAX0tUe6iWp/vLJNEiJ4pYDi8/JXudZGhvqWFOeCQKCQZl8mkI/GSbGXcuPOGB7jmJudqfUuJX+HnMIQdIahqBwoNwYo9FBxFRJZ0vWV9HgHaM4X6FsnyQe/SXaLxLRwnULT+7IdW5I/61BMmY+N3lGhraMIw+/k4ye3Z3L+FEkRT9TGo5frX8yPCQHM2NVZl+aRAjl6oxOnTzoRuM6LpiHCWrhQVRsWCOhtI2XLjqZQ65bs2ZeZYPpBGOwm6BeVyHbchm7U+XI/8z6cV5QSxxH+vmoBPgXDpGOyZISm8MnRsuOhhEOOyUjhpLgpRDGY6RJ746YiSljaD60Tz5FBN1JlvCPA6oJE4XeqTklAMOiUsOUtacn2sXtQFFf6johzQbZNmCD6Yl9UT0s1BCD2g4KrvFAa3fD7nNLIiWIvacps0pteMIYclvSKw6XQwwVJPH5dKPR4Up4C9HivR84w0xxtoLllG0r2hM+Im8vrtDS0GXPrvYFn7m/sWbw="
  file:
    - _packages/**/*.tar.gz
    - _packages/**/*.zip
  file_glob: true
  skip_cleanup: true
  on:
    repo: xobs/toolchain-nextpnr-ecp5
    all_branches: true
    tags: true
branches:
  only:
    # Release tags
    - /^v\d+\.\d+/
    - master
notifications:
  email:
    on_success: change