sudo: required
dist: xenial
language: cpp
matrix:
  include:
  - os: osx
    env: TARGET=darwin
    addons:
      homebrew:
        update: true
        packages:
          - bison
          - flex
          - gawk
          - libffi
          - git
          - python3
          - pkg-config
          - libusb
          - libftdi
          - gnu-sed
          - wget
          - qt5
          - boost
          - boost-python3
          - eigen
  - os: linux
    env: TARGET=linux_x86_64
  # - os: linux
  #   env: TARGET=linux_i686
  # - os: linux
  #   env: TARGET=linux_armv7l
  # - os: linux
  #   env: TARGET=linux_aarch64
  - os: linux
    env: TARGET=windows_x86
  - os: linux
    env: TARGET=windows_amd64
before_script:
- if [[ ${TARGET:0:7} == "windows" ]]; then sudo dpkg --add-architecture i386; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:tes/ams; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y -qq; fi
script:
- bash build.sh $TARGET
- openssl sha1 _packages/**/*.tar.gz
deploy:
  provider: releases
  api_key:
    secure: Mhf7VNrFipZRp+cghK6kK27NhlSVVPTheEelJ7ItgcCfigYtaPwW9xwZb2tjqEdqLeE4o3rmOhYCTXX07ZyF6WwDj68TqJUKa+hvvA+z9akqB3GAGfcdoWWtP7jyXuqE6FNRAapkcTXXwIKZQ89GA0wVq5RY/PXGxa8AwG8mg1FOiEIZgRE3aGeo0wL2Vxuyvd610UHYSuAH29+QcsUZslSFzXURlPUZhMBu4vK/sqUGR8nOzybZm1V2TjANWtCYAVLPh/ZZjUZGNd0OS0KF2inYml6/gedR2r9YZervs5U6Ps3ICvntaHOktJtmKcBl9LTtRnFnfaiOR9FOiAwtxgW7DcRIuGVkB6LQDYhvC2UVaIFjhBCSQfsOX6DnC7Oxmf1vLTYjwC9ymbSZhY8TB/bvgmLNY8c7ge4rnMQPQEyeIzmYQJbskfE/g9YwgVJPIuKYkEOm1FMLpZO7G6XUvQr4vY9zY68DX2eA9CEZQTTzA+HUA05J7ScdX2yitpgavnOZ5gUTAJXPbLZuLbbEd+EPhu8cHHU0W7ykEOc6Atj2JiDwSAO4Xi2dOV7QMz0M9Ak0fpOThbg+l8d3qqDIC6+J00ENEU8H4mNJHTwi19iu+La1G5k1ShCWWgeDf4ygv7ROuxujRnjq4TY/YW3clYttzteOefnnTH8JK5f5oTM=
  file: _packages/**/*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: xobs/toolchain-nextpnr-ice40
    all_branches: true
